/**
 * The storage contract (spec §85).
 *
 * Two implementations sit behind this: S3-compatible object storage for
 * production, and a local-disk driver for development. Everything above this
 * line — uploads, galleries, signatures, contracts — talks only to this
 * interface, so moving from one to the other is an environment change rather
 * than a code change.
 */

export type Visibility = "PUBLIC" | "PRIVATE";

export type UploadResult = {
  bucket: string;
  key: string;
  /** Only for PUBLIC objects; PRIVATE ones are reached through an authorised route */
  publicUrl: string | null;
  contentType: string;
  sizeBytes: number;
};

export type StorageDriver = {
  readonly name: "s3" | "local";
  /** Whether this driver has everything it needs to run */
  isConfigured(): boolean;
  upload(input: {
    key: string;
    body: Buffer;
    contentType: string;
    visibility: Visibility;
  }): Promise<UploadResult>;
  delete(bucket: string, key: string): Promise<void>;
  /**
   * A URL the browser can fetch for a private object, valid for a short time.
   * Only ever called after the caller's session and agency have been checked.
   */
  signedUrl(bucket: string, key: string, expiresInSeconds: number): Promise<string>;
  /** Read a private object back, for routes that stream rather than redirect */
  read(bucket: string, key: string): Promise<Buffer>;
};

export class StorageNotConfiguredError extends Error {
  constructor() {
    super(
      "Object storage is not configured. Set STORAGE_DRIVER=local for development, or the S3_* variables for production.",
    );
    this.name = "StorageNotConfiguredError";
  }
}

export const IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
] as const;

export const MAX_IMAGE_BYTES = 8 * 1024 * 1024;

/**
 * Object keys always start with the agency id, so one tenant's objects sit in a
 * distinguishable prefix and a bucket policy or lifecycle rule can be written
 * per agency later without a migration.
 */
export function buildKey(parts: {
  agencyId: string;
  entity: string;
  entityId: string;
  filename: string;
}): string {
  const extension = parts.filename.includes(".")
    ? parts.filename.split(".").pop()!.toLowerCase().replace(/[^a-z0-9]/g, "")
    : "bin";
  return `agency/${parts.agencyId}/${parts.entity}/${parts.entityId}/${crypto.randomUUID()}.${extension}`;
}

/**
 * Reject anything that could escape the storage root.
 *
 * Keys are generated by `buildKey`, but they round-trip through the database and
 * a URL before they are used to open a file, so they are validated again here.
 */
export function isSafeKey(key: string): boolean {
  if (!key || key.length > 512) return false;
  if (key.startsWith("/") || key.startsWith("\\")) return false;
  if (key.includes("..")) return false;
  if (key.includes("\0")) return false;
  return /^[A-Za-z0-9/._-]+$/.test(key);
}
